package eu.wohlben.qits.projects.api;

import static io.restassured.RestAssured.given;

import eu.wohlben.qits.projects.contracts.GoldenFiles;
import io.quarkus.test.junit.QuarkusTest;
import java.util.regex.Pattern;
import org.junit.jupiter.api.Test;

/**
 * Pins {@code docs/openapi.yml} to the surface this build serves at {@code /projects/q/openapi}.
 * Checking the document in is what turns an API change into a reviewable diff instead of something
 * a caller discovers at runtime.
 *
 * <p><b>It compares by default</b> and fails with a unified diff when the served document moved;
 * {@code -Dgolden.update=true} (or {@code QITS_GOLDEN_UPDATE=true}) rewrites the file instead — the
 * switch every golden here shares ({@link GoldenFiles}). It is a test only because {@code
 * @QuarkusTest} is the cheapest way to stand the application up and read its own document.
 *
 * <p>{@code info.version} is the release version and is left out of the comparison: every release
 * bumps the pom, so comparing it would fail every release request's gate on a line no API change
 * moved. A rewrite still writes the version it served.
 *
 * <p>The test classpath is indexed too, so any {@code @Path} resource under {@code src/test} lands
 * in the committed document unless it is {@code @Operation(hidden = true)} — see {@code
 * IdentityEchoResource}.
 */
@QuarkusTest
public class OpenApiSchemaExportTest {

  /** The one two-space-indented {@code version:} key in the document is {@code info.version}. */
  private static final Pattern INFO_VERSION = Pattern.compile("(?m)^  version: .*$");

  @Test
  public void exportOpenApiSchema() {
    String schema = given().when().get("/projects/q/openapi").then().statusCode(200).extract().asString();

    String header =
        "# THIS FILE IS GENERATED BY OpenApiSchemaExportTest — DO NOT EDIT MANUALLY.\n"
            + "# Run `./mvnw -pl service -am test -Dtest=OpenApiSchemaExportTest"
            + " -Dsurefire.failIfNoSpecifiedTests=false -Dgolden.update=true` to regenerate.\n";

    GoldenFiles.compareOrWrite(
        GoldenFiles.repositoryRoot().resolve("docs").resolve("openapi.yml"),
        header + schema,
        text -> INFO_VERSION.matcher(text).replaceAll("  version: <release version>"));
  }
}
